export enum SPYCHECK_OPTION
{
    CUSTOM_QUESTION_ENABLE = 'CUSTOM_QUESTION_ENABLE',
    CUSTOM_QUESTION_TIME = 'CUSTOM_QUESTION_TIME',
    ANSWER_SELECT_TIME = 'ANSWER_SELECT_TIME',
    SPY_GUESS_TIME = 'SPY_GUESS_TIME',
    SPY_COUNT = 'SPY_COUNT',
}