export enum BGM_TYPE
{
    BELL = 'bell.webm',
    COUNTDOWN_10 = 'countdown10.webm',
    ENDING = 'ENDING.webm',
    FAIL = 'FAIL.webm',
    MATCH_FIND = 'MATCH_FIND.webm',
    MATCHING = 'MATCHING.webm',
    PLING = 'pling.webm',
    ROUND_ALARM = 'ROUND_ALARM.webm',
    SCORE_ALARM = 'SCORE_ALARM.webm',
    SUCCESS = 'SUCCESS.webm',
    FAILOVER = 'FAILOVER.webm',
    DOOR_BELL = 'DOOR_BELL.webm',
    CHAT = 'CHAT.webm',
    LOBBY_CREATED = 'MATCHING.webm',
    GAME_START = 'GAME_START.webm',
    JOIN = 'DOOR_BELL.webm',
    GUN_SHOT = 'GUN_SHOT.webm',
    FINISH = 'FINISH.webm',
    ERROR = 'ERROR.webm',
    GRAND_FATHER_11_MONTH = 'GRAND_FATHER_11_MONTH.webm',
    PUNCH = 'PUNCH.webm',
}